/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.millburn.kiosk.ServerInitializer;

import static org.junit.Assert.*;

public class ServerTest {
    @Test public void testAppHasAGreeting() {
        ServerInitializer classUnderTest = new ServerInitializer();
        assertNotNull("app should have a greeting", classUnderTest);
    }
}
